INSERT INTO models (brand, name) VALUES ('Acura', 'ILX');
INSERT INTO models (brand, name) VALUES ('Acura', 'Integra');
INSERT INTO models (brand, name) VALUES ('Acura', 'MDX');
INSERT INTO models (brand, name) VALUES ('Acura', 'RDX');
INSERT INTO models (brand, name) VALUES ('Acura', 'TLX');
INSERT INTO models (brand, name) VALUES ('Alfa Romeo', 'Giulia');
INSERT INTO models (brand, name) VALUES ('Alfa Romeo', 'Stelvio');
INSERT INTO models (brand, name) VALUES ('Alfa Romeo', 'Tonale');
INSERT INTO models (brand, name) VALUES ('Audi', 'A3');
INSERT INTO models (brand, name) VALUES ('Audi', 'A4');
INSERT INTO models (brand, name) VALUES ('Audi', 'A4 allroad');
INSERT INTO models (brand, name) VALUES ('Audi', 'A5');
INSERT INTO models (brand, name) VALUES ('Audi', 'A6');
INSERT INTO models (brand, name) VALUES ('Audi', 'A6 allroad');
INSERT INTO models (brand, name) VALUES ('Audi', 'A7');
INSERT INTO models (brand, name) VALUES ('Audi', 'A8');
INSERT INTO models (brand, name) VALUES ('Audi', 'e-tron');
INSERT INTO models (brand, name) VALUES ('Audi', 'e-tron GT');
INSERT INTO models (brand, name) VALUES ('Audi', 'e-tron S');
INSERT INTO models (brand, name) VALUES ('Audi', 'e-tron S Sportback');
INSERT INTO models (brand, name) VALUES ('Audi', 'e-tron Sportback');
INSERT INTO models (brand, name) VALUES ('Audi', 'Q3');
INSERT INTO models (brand, name) VALUES ('Audi', 'Q5');
INSERT INTO models (brand, name) VALUES ('Audi', 'Q5 Sportback');
INSERT INTO models (brand, name) VALUES ('Audi', 'Q7');
INSERT INTO models (brand, name) VALUES ('Audi', 'Q8');
INSERT INTO models (brand, name) VALUES ('Audi', 'R8');
INSERT INTO models (brand, name) VALUES ('Audi', 'RS 3');
INSERT INTO models (brand, name) VALUES ('Audi', 'RS 5');
INSERT INTO models (brand, name) VALUES ('Audi', 'RS 6');
INSERT INTO models (brand, name) VALUES ('Audi', 'RS 7');
INSERT INTO models (brand, name) VALUES ('Audi', 'RS e-tron GT');
INSERT INTO models (brand, name) VALUES ('Audi', 'RS Q8');
INSERT INTO models (brand, name) VALUES ('Audi', 'S3');
INSERT INTO models (brand, name) VALUES ('Audi', 'S4');
INSERT INTO models (brand, name) VALUES ('Audi', 'S5');
INSERT INTO models (brand, name) VALUES ('Audi', 'S6');
INSERT INTO models (brand, name) VALUES ('Audi', 'S7');
INSERT INTO models (brand, name) VALUES ('Audi', 'S8');
INSERT INTO models (brand, name) VALUES ('Audi', 'SQ5');
INSERT INTO models (brand, name) VALUES ('Audi', 'SQ5 Sportback');
INSERT INTO models (brand, name) VALUES ('Audi', 'SQ7');
INSERT INTO models (brand, name) VALUES ('Audi', 'SQ8');
INSERT INTO models (brand, name) VALUES ('Audi', 'TT');
INSERT INTO models (brand, name) VALUES ('BMW', '2 Series');
INSERT INTO models (brand, name) VALUES ('BMW', '3 Series');
INSERT INTO models (brand, name) VALUES ('BMW', '4 Series');
INSERT INTO models (brand, name) VALUES ('BMW', '5 Series');
INSERT INTO models (brand, name) VALUES ('BMW', '7 Series');
INSERT INTO models (brand, name) VALUES ('BMW', '8 Series');
INSERT INTO models (brand, name) VALUES ('BMW', 'i4');
INSERT INTO models (brand, name) VALUES ('BMW', 'i7');
INSERT INTO models (brand, name) VALUES ('BMW', 'iX');
INSERT INTO models (brand, name) VALUES ('BMW', 'M3');
INSERT INTO models (brand, name) VALUES ('BMW', 'M4');
INSERT INTO models (brand, name) VALUES ('BMW', 'M5');
INSERT INTO models (brand, name) VALUES ('BMW', 'M8');
INSERT INTO models (brand, name) VALUES ('BMW', 'X1');
INSERT INTO models (brand, name) VALUES ('BMW', 'X2');
INSERT INTO models (brand, name) VALUES ('BMW', 'X3');
INSERT INTO models (brand, name) VALUES ('BMW', 'X3 M');
INSERT INTO models (brand, name) VALUES ('BMW', 'X4');
INSERT INTO models (brand, name) VALUES ('BMW', 'X5');
INSERT INTO models (brand, name) VALUES ('BMW', 'X5 M');
INSERT INTO models (brand, name) VALUES ('BMW', 'X6');
INSERT INTO models (brand, name) VALUES ('BMW', 'X7');
INSERT INTO models (brand, name) VALUES ('Buick', 'Enclave');
INSERT INTO models (brand, name) VALUES ('Buick', 'Encore');
INSERT INTO models (brand, name) VALUES ('Buick', 'Encore GX');
INSERT INTO models (brand, name) VALUES ('Buick', 'Envision');
INSERT INTO models (brand, name) VALUES ('Cadillac', 'CT4');
INSERT INTO models (brand, name) VALUES ('Cadillac', 'CT5');
INSERT INTO models (brand, name) VALUES ('Cadillac', 'Escalade');
INSERT INTO models (brand, name) VALUES ('Cadillac', 'Escalade ESV');
INSERT INTO models (brand, name) VALUES ('Cadillac', 'LYRIQ');
INSERT INTO models (brand, name) VALUES ('Cadillac', 'XT4');
INSERT INTO models (brand, name) VALUES ('Cadillac', 'XT5');
INSERT INTO models (brand, name) VALUES ('Cadillac', 'XT6');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Blazer');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Bolt EUV');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Bolt EV');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Camaro');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Colorado Crew Cab');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Corvette');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Equinox');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Express 2500 Cargo');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Express 3500 Cargo');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Malibu');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Silverado 1500 Crew Cab');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Silverado 1500 Regular Cab');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Silverado 2500 HD Crew Cab');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Silverado 2500 HD Double Cab');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Silverado 2500 HD Regular Cab');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Silverado 3500 HD Regular Cab');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Spark');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Suburban');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Tahoe');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Trailblazer');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Traverse');
INSERT INTO models (brand, name) VALUES ('Chevrolet', 'Trax');
INSERT INTO models (brand, name) VALUES ('Chrysler', '300');
INSERT INTO models (brand, name) VALUES ('Chrysler', 'Pacifica');
INSERT INTO models (brand, name) VALUES ('Chrysler', 'Pacifica Hybrid');
INSERT INTO models (brand, name) VALUES ('Dodge', 'Challenger');
INSERT INTO models (brand, name) VALUES ('Dodge', 'Charger');
INSERT INTO models (brand, name) VALUES ('Dodge', 'Durango');
INSERT INTO models (brand, name) VALUES ('Dodge', 'Hornet');
INSERT INTO models (brand, name) VALUES ('Ford', 'Bronco');
INSERT INTO models (brand, name) VALUES ('Ford', 'Bronco Sport');
INSERT INTO models (brand, name) VALUES ('Ford', 'Edge');
INSERT INTO models (brand, name) VALUES ('Ford', 'Escape');
INSERT INTO models (brand, name) VALUES ('Ford', 'E-Transit 350 Cargo Van');
INSERT INTO models (brand, name) VALUES ('Ford', 'Expedition');
INSERT INTO models (brand, name) VALUES ('Ford', 'Expedition MAX');
INSERT INTO models (brand, name) VALUES ('Ford', 'Explorer');
INSERT INTO models (brand, name) VALUES ('Ford', 'F150 Lightning');
INSERT INTO models (brand, name) VALUES ('Ford', 'F150 SuperCrew Cab');
INSERT INTO models (brand, name) VALUES ('Ford', 'Maverick');
INSERT INTO models (brand, name) VALUES ('Ford', 'Mustang');
INSERT INTO models (brand, name) VALUES ('Ford', 'Mustang MACH-E');
INSERT INTO models (brand, name) VALUES ('Ford', 'Ranger SuperCab');
INSERT INTO models (brand, name) VALUES ('Ford', 'Ranger SuperCrew');
INSERT INTO models (brand, name) VALUES ('Ford', 'Transit Connect Cargo Van');
INSERT INTO models (brand, name) VALUES ('Ford', 'Transit Connect Passenger Wagon');
INSERT INTO models (brand, name) VALUES ('Genesis', 'Electrified G80');
INSERT INTO models (brand, name) VALUES ('Genesis', 'G70');
INSERT INTO models (brand, name) VALUES ('Genesis', 'G80');
INSERT INTO models (brand, name) VALUES ('Genesis', 'G90');
INSERT INTO models (brand, name) VALUES ('Genesis', 'GV60');
INSERT INTO models (brand, name) VALUES ('Genesis', 'GV70');
INSERT INTO models (brand, name) VALUES ('Genesis', 'GV80');
INSERT INTO models (brand, name) VALUES ('GMC', 'Acadia');
INSERT INTO models (brand, name) VALUES ('GMC', 'Canyon Crew Cab');
INSERT INTO models (brand, name) VALUES ('GMC', 'Hummer EV Pickup');
INSERT INTO models (brand, name) VALUES ('GMC', 'Savana 2500 Cargo');
INSERT INTO models (brand, name) VALUES ('GMC', 'Savana 2500 Passenger');
INSERT INTO models (brand, name) VALUES ('GMC', 'Savana 3500 Cargo');
INSERT INTO models (brand, name) VALUES ('GMC', 'Savana 3500 Passenger');
INSERT INTO models (brand, name) VALUES ('GMC', 'Sierra 1500 Crew Cab');
INSERT INTO models (brand, name) VALUES ('GMC', 'Sierra 1500 Double Cab');
INSERT INTO models (brand, name) VALUES ('GMC', 'Sierra 1500 Regular Cab');
INSERT INTO models (brand, name) VALUES ('GMC', 'Sierra 2500 HD Regular Cab');
INSERT INTO models (brand, name) VALUES ('GMC', 'Sierra 3500 HD Regular Cab');
INSERT INTO models (brand, name) VALUES ('GMC', 'Terrain');
INSERT INTO models (brand, name) VALUES ('GMC', 'Yukon');
INSERT INTO models (brand, name) VALUES ('GMC', 'Yukon XL');
INSERT INTO models (brand, name) VALUES ('Honda', 'Accord');
INSERT INTO models (brand, name) VALUES ('Honda', 'Civic');
INSERT INTO models (brand, name) VALUES ('Honda', 'CR-V');
INSERT INTO models (brand, name) VALUES ('Honda', 'HR-V');
INSERT INTO models (brand, name) VALUES ('Honda', 'Insight');
INSERT INTO models (brand, name) VALUES ('Honda', 'Odyssey');
INSERT INTO models (brand, name) VALUES ('Honda', 'Passport');
INSERT INTO models (brand, name) VALUES ('Honda', 'Pilot');
INSERT INTO models (brand, name) VALUES ('Honda', 'Ridgeline');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Elantra');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Elantra Hybrid');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'IONIQ 5');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Ioniq Hybrid');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Kona');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Kona Electric');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Kona N');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Palisade');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Santa Cruz');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Santa Fe');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Santa Fe Plug-in Hybrid');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Sonata');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Sonata Hybrid');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Tucson');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Tucson Hybrid');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Tucson Plug-in Hybrid');
INSERT INTO models (brand, name) VALUES ('Hyundai', 'Venue');
INSERT INTO models (brand, name) VALUES ('INFINITI', 'Q50');
INSERT INTO models (brand, name) VALUES ('INFINITI', 'QX50');
INSERT INTO models (brand, name) VALUES ('INFINITI', 'QX55');
INSERT INTO models (brand, name) VALUES ('INFINITI', 'QX60');
INSERT INTO models (brand, name) VALUES ('Jaguar', 'E-PACE');
INSERT INTO models (brand, name) VALUES ('Jaguar', 'F-PACE');
INSERT INTO models (brand, name) VALUES ('Jaguar', 'F-TYPE');
INSERT INTO models (brand, name) VALUES ('Jaguar', 'I-PACE');
INSERT INTO models (brand, name) VALUES ('Jaguar', 'XF');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Compass');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Gladiator');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Grand Cherokee');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Grand Cherokee 4xe');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Grand Cherokee L');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Grand Wagoneer');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Grand Wagoneer L');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Renegade');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Wagoneer');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Wagoneer L');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Wrangler');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Wrangler Unlimited');
INSERT INTO models (brand, name) VALUES ('Jeep', 'Wrangler Unlimited 4xe');
INSERT INTO models (brand, name) VALUES ('Kia', 'Carnival');
INSERT INTO models (brand, name) VALUES ('Kia', 'EV6');
INSERT INTO models (brand, name) VALUES ('Kia', 'Forte');
INSERT INTO models (brand, name) VALUES ('Kia', 'K5');
INSERT INTO models (brand, name) VALUES ('Kia', 'Niro');
INSERT INTO models (brand, name) VALUES ('Kia', 'Niro EV');
INSERT INTO models (brand, name) VALUES ('Kia', 'Niro Plug-in Hybrid');
INSERT INTO models (brand, name) VALUES ('Kia', 'Rio');
INSERT INTO models (brand, name) VALUES ('Kia', 'Seltos');
INSERT INTO models (brand, name) VALUES ('Kia', 'Sorento');
INSERT INTO models (brand, name) VALUES ('Kia', 'Sorento Hybrid');
INSERT INTO models (brand, name) VALUES ('Kia', 'Sorento Plug-in Hybrid');
INSERT INTO models (brand, name) VALUES ('Kia', 'Soul');
INSERT INTO models (brand, name) VALUES ('Kia', 'Sportage');
INSERT INTO models (brand, name) VALUES ('Kia', 'Sportage Hybrid');
INSERT INTO models (brand, name) VALUES ('Kia', 'Sportage Plug-in Hybrid');
INSERT INTO models (brand, name) VALUES ('Kia', 'Stinger');
INSERT INTO models (brand, name) VALUES ('Kia', 'Telluride');
INSERT INTO models (brand, name) VALUES ('Land Rover', 'Defender 110');
INSERT INTO models (brand, name) VALUES ('Land Rover', 'Defender 130');
INSERT INTO models (brand, name) VALUES ('Land Rover', 'Defender 90');
INSERT INTO models (brand, name) VALUES ('Land Rover', 'Discovery');
INSERT INTO models (brand, name) VALUES ('Land Rover', 'Discovery Sport');
INSERT INTO models (brand, name) VALUES ('Land Rover', 'Range Rover');
INSERT INTO models (brand, name) VALUES ('Land Rover', 'Range Rover Evoque');
INSERT INTO models (brand, name) VALUES ('Land Rover', 'Range Rover Sport');
INSERT INTO models (brand, name) VALUES ('Land Rover', 'Range Rover Velar');
INSERT INTO models (brand, name) VALUES ('Lexus', 'ES');
INSERT INTO models (brand, name) VALUES ('Lexus', 'GX');
INSERT INTO models (brand, name) VALUES ('Lexus', 'IS');
INSERT INTO models (brand, name) VALUES ('Lexus', 'LS');
INSERT INTO models (brand, name) VALUES ('Lexus', 'LX');
INSERT INTO models (brand, name) VALUES ('Lexus', 'NX');
INSERT INTO models (brand, name) VALUES ('Lexus', 'RX');
INSERT INTO models (brand, name) VALUES ('Lexus', 'RZ');
INSERT INTO models (brand, name) VALUES ('Lexus', 'TX');
INSERT INTO models (brand, name) VALUES ('Lexus', 'UX');
INSERT INTO models (brand, name) VALUES ('Lincoln', 'Aviator');
INSERT INTO models (brand, name) VALUES ('Lincoln', 'Corsair');
INSERT INTO models (brand, name) VALUES ('Lincoln', 'Nautilus');
INSERT INTO models (brand, name) VALUES ('Lincoln', 'Navigator');
INSERT INTO models (brand, name) VALUES ('Lincoln', 'Navigator L');
INSERT INTO models (brand, name) VALUES ('Maserati', 'Grecale');
INSERT INTO models (brand, name) VALUES ('MAZDA', 'CX-30');
INSERT INTO models (brand, name) VALUES ('MAZDA', 'CX-5');
INSERT INTO models (brand, name) VALUES ('MAZDA', 'CX-50');
INSERT INTO models (brand, name) VALUES ('MAZDA', 'CX-9');
INSERT INTO models (brand, name) VALUES ('MAZDA', 'CX-90');
INSERT INTO models (brand, name) VALUES ('MAZDA', 'MAZDA3');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'C-Class');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'E-Class');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'GLA');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'GLB');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'GLC');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'GLE');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'GLS');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'Mercedes-EQ EQB');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'Mercedes-EQ EQE');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'Mercedes-EQ EQE SUV');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'Mercedes-EQ EQS');
INSERT INTO models (brand, name) VALUES ('Mercedes-Benz', 'Mercedes-EQ EQS SUV');
INSERT INTO models (brand, name) VALUES ('MINI', 'Clubman');
INSERT INTO models (brand, name) VALUES ('MINI', 'Convertible');
INSERT INTO models (brand, name) VALUES ('MINI', 'Countryman');
INSERT INTO models (brand, name) VALUES ('MINI', 'Hardtop 2 Door');
INSERT INTO models (brand, name) VALUES ('MINI', 'Hardtop 4 Door');
INSERT INTO models (brand, name) VALUES ('Mitsubishi', 'Eclipse Cross');
INSERT INTO models (brand, name) VALUES ('Mitsubishi', 'Mirage');
INSERT INTO models (brand, name) VALUES ('Mitsubishi', 'Mirage G4');
INSERT INTO models (brand, name) VALUES ('Mitsubishi', 'Outlander');
INSERT INTO models (brand, name) VALUES ('Mitsubishi', 'Outlander PHEV');
INSERT INTO models (brand, name) VALUES ('Mitsubishi', 'Outlander Sport');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Altima');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Ariya');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Armada');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Frontier Crew Cab');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Frontier King Cab');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Kicks');
INSERT INTO models (brand, name) VALUES ('Nissan', 'LEAF');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Maxima');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Murano');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Pathfinder');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Rogue');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Rogue Sport');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Sentra');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Titan Crew Cab');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Titan King Cab');
INSERT INTO models (brand, name) VALUES ('Nissan', 'TITAN XD Crew Cab');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Versa');
INSERT INTO models (brand, name) VALUES ('Nissan', 'Z');
INSERT INTO models (brand, name) VALUES ('Polestar', '2');
INSERT INTO models (brand, name) VALUES ('Polestar', '3');
INSERT INTO models (brand, name) VALUES ('Porsche', '718 Spyder');
INSERT INTO models (brand, name) VALUES ('Porsche', 'Cayenne');
INSERT INTO models (brand, name) VALUES ('Porsche', 'Macan');
INSERT INTO models (brand, name) VALUES ('Ram', '1500 Classic Crew Cab');
INSERT INTO models (brand, name) VALUES ('Ram', '1500 Classic Quad Cab');
INSERT INTO models (brand, name) VALUES ('Ram', '1500 Classic Regular Cab');
INSERT INTO models (brand, name) VALUES ('Ram', '1500 Crew Cab');
INSERT INTO models (brand, name) VALUES ('Ram', '1500 Quad Cab');
INSERT INTO models (brand, name) VALUES ('Ram', 'ProMaster Cargo Van');
INSERT INTO models (brand, name) VALUES ('Ram', 'ProMaster Window Van');
INSERT INTO models (brand, name) VALUES ('Subaru', 'Ascent');
INSERT INTO models (brand, name) VALUES ('Subaru', 'BRZ');
INSERT INTO models (brand, name) VALUES ('Subaru', 'Crosstrek');
INSERT INTO models (brand, name) VALUES ('Subaru', 'Forester');
INSERT INTO models (brand, name) VALUES ('Subaru', 'Impreza');
INSERT INTO models (brand, name) VALUES ('Subaru', 'Legacy');
INSERT INTO models (brand, name) VALUES ('Subaru', 'Outback');
INSERT INTO models (brand, name) VALUES ('Subaru', 'Solterra');
INSERT INTO models (brand, name) VALUES ('Subaru', 'WRX');
INSERT INTO models (brand, name) VALUES ('Tesla', 'Cybertruck');
INSERT INTO models (brand, name) VALUES ('Tesla', 'Model 3');
INSERT INTO models (brand, name) VALUES ('Tesla', 'Model S');
INSERT INTO models (brand, name) VALUES ('Tesla', 'Model X');
INSERT INTO models (brand, name) VALUES ('Tesla', 'Model Y');
INSERT INTO models (brand, name) VALUES ('Toyota', '4Runner');
INSERT INTO models (brand, name) VALUES ('Toyota', '86');
INSERT INTO models (brand, name) VALUES ('Toyota', 'bZ4X');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Camry');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Camry Hybrid');
INSERT INTO models (brand, name) VALUES ('Toyota', 'C-HR');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Corolla');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Corolla Cross');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Corolla Cross Hybrid');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Corolla Hatchback');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Corolla Hybrid');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Crown');
INSERT INTO models (brand, name) VALUES ('Toyota', 'GR Supra');
INSERT INTO models (brand, name) VALUES ('Toyota', 'GR86');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Highlander');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Highlander Hybrid');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Prius');
INSERT INTO models (brand, name) VALUES ('Toyota', 'RAV4');
INSERT INTO models (brand, name) VALUES ('Toyota', 'RAV4 Hybrid');
INSERT INTO models (brand, name) VALUES ('Toyota', 'RAV4 Prime');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Sequoia');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Sienna');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Tacoma Access Cab');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Tundra CrewMax');
INSERT INTO models (brand, name) VALUES ('Toyota', 'Venza');
INSERT INTO models (brand, name) VALUES ('VinFast', 'VF 8');
INSERT INTO models (brand, name) VALUES ('VinFast', 'VF 9');
INSERT INTO models (brand, name) VALUES ('Volkswagen', 'Arteon');
INSERT INTO models (brand, name) VALUES ('Volkswagen', 'Atlas');
INSERT INTO models (brand, name) VALUES ('Volkswagen', 'Atlas Cross Sport');
INSERT INTO models (brand, name) VALUES ('Volkswagen', 'Golf GTI');
INSERT INTO models (brand, name) VALUES ('Volkswagen', 'Golf R');
INSERT INTO models (brand, name) VALUES ('Volkswagen', 'ID.4');
INSERT INTO models (brand, name) VALUES ('Volkswagen', 'Jetta');
INSERT INTO models (brand, name) VALUES ('Volkswagen', 'Jetta GLI');
INSERT INTO models (brand, name) VALUES ('Volkswagen', 'Taos');
INSERT INTO models (brand, name) VALUES ('Volkswagen', 'Tiguan');
INSERT INTO models (brand, name) VALUES ('Volvo', 'C40 Recharge');
INSERT INTO models (brand, name) VALUES ('Volvo', 'S60');
INSERT INTO models (brand, name) VALUES ('Volvo', 'S90');
INSERT INTO models (brand, name) VALUES ('Volvo', 'V60');
INSERT INTO models (brand, name) VALUES ('Volvo', 'V90');
INSERT INTO models (brand, name) VALUES ('Volvo', 'XC40');
INSERT INTO models (brand, name) VALUES ('Volvo', 'XC40 Recharge');
INSERT INTO models (brand, name) VALUES ('Volvo', 'XC60');
INSERT INTO models (brand, name) VALUES ('Volvo', 'XC90');